"""mixin

Revision ID: 524b7ac65c95
Revises: 7a7780f31192
Create Date: 2024-02-27 19:44:14.938815

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "524b7ac65c95"
down_revision: Union[str, None] = "7a7780f31192"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "<built-in method lower of str object at 0x7f26c51cb9b0>s",
        sa.Column("first_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=True),
        sa.Column("info", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "post",
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("text", sa.Text(), server_default="", nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("<built-in method lower of str object at 0x7fa8c6dcbaf0>s")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "<built-in method lower of str object at 0x7fa8c6dcbaf0>s",
        sa.Column("title", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "text",
            sa.TEXT(),
            server_default=sa.text("''::text"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text(
                "nextval('\"<built-in method lower of str object at 0x7fa8c6dcbaf0>s_id_seq\"'::regclass)"
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="<built-in method lower of str object at 0x7fa8c6dc_user_id_fkey",
        ),
        sa.PrimaryKeyConstraint(
            "id", name="<built-in method lower of str object at 0x7fa8c6dcbaf0>s_pkey"
        ),
    )
    op.drop_table("post")
    op.drop_table("<built-in method lower of str object at 0x7f26c51cb9b0>s")
    # ### end Alembic commands ###
